config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :ingredients, only: [:index, :show]
    resources :doses, only: [:show, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  attr_reader :ingredient, :dose

  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: [:ingredient_id] }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, foreign_key: "ingredient_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new"
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

  def set_cocktail
    Cocktail.find(params[:id]) == nil ? @cocktail = Cocktail.find(params[:cocktail_id]) : @cocktail = Cocktail.find(params[:id])
    Dose.where(cocktail_id: params[:id]).empty? ? @doses = Dose.where(cocktail_id: params[:cocktail_id]) : @doses = Dose.where(cocktail_id: params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = params[:cocktail_id]
    @dose.ingredient_id = params[:dose][:ingredient_id]
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @doses = Dose.where(cocktail_id: params[:cocktail_id])
      render '/cocktails/show'
    end
  end

  def destroy
    # if params[:id].nil?
      @dose = Dose.find(params[:id])
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose.destroy
      redirect_to cocktail_path(@cocktail)
    # else
    #   @cocktail = Cocktail.find(params[:id])
    #   @dose = Dose.find(params[:cocktail_id])
    #   @dose.destroy
    #   redirect_to cocktail_path(@cocktail)
    # end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/cocktails">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/cocktails/new">Add New Cocktail <span class="sr-only">(current)</span></a>
    </ul>
  </div>
</nav>


<div class="cards">
  <% @cocktails.each do |cocktail| %>
  <%= <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{cocktail.image_url})">%>
    <%= link_to "#{cocktail.name}", cocktail_path(cocktail) %>
  </div>
   <% end %>
</div>

app/views/cocktails/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/cocktails">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/cocktails/new">Add New Cocktail <span class="sr-only">(current)</span></a>
    </ul>
  </div>
</nav>

<div class="container">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, "Add cocktail", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/cocktails">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/cocktails/new">Add New Cocktail <span class="sr-only">(current)</span></a>
    </ul>
  </div>
</nav>

<div class="container">
  <h1><%= @cocktail.name %></h1>
  <h3>Recipe</h3>
  <div class="flex-display">
    <div>
      <%= image_tag("#{@cocktail.name}.jpg", alt: @cocktail.name, class: "img-thumbnail") %>
    </div>
    <div>
        <% @doses.each do |dose| %>
        <div class="revealRemove"><%= dose.description %> <%= Ingredient.find(dose.ingredient_id).name %> <%= link_to 'Remove ingredient', cocktail_dose_path(@cocktail, dose), method: :delete, class: "removeLink", data: { confirm: 'Are you certain you want to delete this?' } %><br></div>
        <% end %>
        <%= button_tag "Add ingredients?", id: 'hideBtn' %>
        <div id="hiddenIngredientForm">
          <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :description, placeholder: "4 oz, 1 tsp, etc." %>
            <%= f.association :ingredient, collection: Ingredient.order('name ASC'), input_html: { class: 'select2' } %>
            <%= f.button :submit, "Add ingredient", class: "btn btn-primary" %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="flex-options">
    <p><%= link_to 'Back', cocktails_path %> <%= link_to 'Add Ingredient', new_cocktail_dose_path(@cocktail) %></p>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1><%= "Add dose to #{@cocktail.name}" %></h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description, placeholder: "4 oz, 1 tsp, etc." %>
    <%= f.association :ingredient, collection: Ingredient.order('name ASC'), input_html: { class: 'select2' } %>
    <%= f.button :submit, "Add dose", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>